### ISSUE TITLE
期待后台管理功能

### ISSUE THREAD

**Issue by tianyunperfect** [oyps/poncon-short-link#1]
- 短链查询、长链查询
- 链接动态修改等。
提点意见，可以忽略。

**Comment by iuroc** [comment]
嗯嗯，会考虑

其实，管理员直接登录 **数据库面板** 去查询好像更香

**Comment by tianyunperfect** [comment]
> 嗯嗯，会考虑
> 
> 其实，管理员直接登录 **数据库面板** 去查询好像更香

我用你的源码搭建了一个，目前就是这样干的，缺点是一般远程的库都不让本地访问的，因为有安全隐患。
感谢啊。
